//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDanhMucKhoanThu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ThanhToan
    {
        public string Idtt { get; set; }
        public string Mssv { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<int> SoThe { get; set; }
        public string TenThe { get; set; }
        public Nullable<int> So { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    }
}
