//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDanhMucKhoanThu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DangKy
    {
        public string MaDangKy { get; set; }
        public string Mssv { get; set; }
        public string MaHocKi { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public string MaMH { get; set; }
    }
}
