//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDanhMucKhoanThu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PhieuThu
    {
        public string SoPhieu { get; set; }
        public string Mssv { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> SoTienThu { get; set; }
        public string DonViThu { get; set; }
        public string TrangThai { get; set; }
    }
}
