//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDanhMucKhoanThu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ThucTap_DoAnEntities1 : DbContext
    {
        public ThucTap_DoAnEntities1()
            : base("name=ThucTap_DoAnEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_ChiTietPhieuThu> TBL_ChiTietPhieuThu { get; set; }
        public DbSet<TBL_KhoanThuMonHoc> TBL_KhoanThuMonHoc { get; set; }
        public DbSet<TBL_PhieuThu> TBL_PhieuThu { get; set; }
        public DbSet<TBL_SinhVien> TBL_SinhVien { get; set; }
        public DbSet<TBL_ThanhToan> TBL_ThanhToan { get; set; }
        public DbSet<TBL_DangKy> TBL_DangKy { get; set; }
    
        public virtual int sp_Delete_KhoanThu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_KhoanThu", idParameter);
        }
    
        public virtual ObjectResult<sp_GetSinhVien_Result> sp_GetSinhVien(string mssv, string matkhau)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSinhVien_Result>("sp_GetSinhVien", mssvParameter, matkhauParameter);
        }
    
        public virtual int sp_Insert_KhoanThu(string mamh, string tenmh, Nullable<int> sotc, Nullable<int> sotiet, Nullable<decimal> dongia)
        {
            var mamhParameter = mamh != null ?
                new ObjectParameter("Mamh", mamh) :
                new ObjectParameter("Mamh", typeof(string));
    
            var tenmhParameter = tenmh != null ?
                new ObjectParameter("Tenmh", tenmh) :
                new ObjectParameter("Tenmh", typeof(string));
    
            var sotcParameter = sotc.HasValue ?
                new ObjectParameter("Sotc", sotc) :
                new ObjectParameter("Sotc", typeof(int));
    
            var sotietParameter = sotiet.HasValue ?
                new ObjectParameter("Sotiet", sotiet) :
                new ObjectParameter("Sotiet", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("Dongia", dongia) :
                new ObjectParameter("Dongia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_KhoanThu", mamhParameter, tenmhParameter, sotcParameter, sotietParameter, dongiaParameter);
        }
    
        public virtual ObjectResult<sp_KhoanThu_Result> sp_KhoanThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KhoanThu_Result>("sp_KhoanThu");
        }
    
        public virtual int sp_Update_KhoanThu(Nullable<int> id, string mamh, string tenmh, Nullable<int> sotc, Nullable<int> sotiet, Nullable<decimal> dongia)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var mamhParameter = mamh != null ?
                new ObjectParameter("Mamh", mamh) :
                new ObjectParameter("Mamh", typeof(string));
    
            var tenmhParameter = tenmh != null ?
                new ObjectParameter("Tenmh", tenmh) :
                new ObjectParameter("Tenmh", typeof(string));
    
            var sotcParameter = sotc.HasValue ?
                new ObjectParameter("Sotc", sotc) :
                new ObjectParameter("Sotc", typeof(int));
    
            var sotietParameter = sotiet.HasValue ?
                new ObjectParameter("Sotiet", sotiet) :
                new ObjectParameter("Sotiet", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("Dongia", dongia) :
                new ObjectParameter("Dongia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_KhoanThu", idParameter, mamhParameter, tenmhParameter, sotcParameter, sotietParameter, dongiaParameter);
        }

        internal object sp_Insert_KhoanThu()
        {
            throw new NotImplementedException();
        }
    }
}
